"""
Module 11: Therapeutic Hypotheses

Drug-pathway mapping and therapeutic hypothesis generation for autism genetics analysis.

This module provides:
- DrugTargetDatabase: Curated drug-target-pathway relationships
- PathwayDrugMapper: Maps disrupted pathways to potential drug candidates
- HypothesisRanker: Ranks therapeutic hypotheses by evidence
- EvidenceScorer: Scores hypotheses on biological plausibility and safety

IMPORTANT: All hypotheses generated by this module are RESEARCH HYPOTHESES only.
They require clinical validation before any therapeutic consideration.

Example usage:
    from modules.11_therapeutic_hypotheses import (
        DrugTargetDatabase,
        PathwayDrugMapper,
        HypothesisRanker,
        EvidenceScorer,
        TherapeuticHypothesis,
        create_sample_drug_database,
    )

    # Load drug database
    db = create_sample_drug_database()

    # Create mapper and ranker
    mapper = PathwayDrugMapper(db)
    scorer = EvidenceScorer()
    ranker = HypothesisRanker(mapper, scorer)

    # Get disrupted pathways (from Module 07)
    pathway_scores = {
        "synaptic_transmission": 2.5,
        "chromatin_remodeling": 1.8,
    }

    # Generate ranked hypotheses
    result = ranker.rank(pathway_scores=pathway_scores)

    # Review results
    for hyp in result.top_hypotheses:
        print(hyp.summary())
"""

import sys
from pathlib import Path

# Add module to path for imports
_module_dir = Path(__file__).parent
if str(_module_dir) not in sys.path:
    sys.path.insert(0, str(_module_dir))

# Pathway-drug mapping
from pathway_drug_mapping import (
    DrugMechanism,
    DrugStatus,
    DrugCandidate,
    DrugTargetDatabase,
    PathwayDrugMapperConfig,
    PathwayDrugMapper,
    create_sample_drug_database,
)

# Evidence scoring
from evidence import (
    EvidenceLevel,
    SafetyFlag,
    EvidenceScore,
    EvidenceScorerConfig,
    EvidenceScorer,
    create_sample_evidence_databases,
)

# Hypothesis ranking
from ranking import (
    TherapeuticHypothesis,
    RankingConfig,
    RankingResult,
    HypothesisRanker,
    create_hypothesis_ranker,
)

__all__ = [
    # Drug mapping
    "DrugMechanism",
    "DrugStatus",
    "DrugCandidate",
    "DrugTargetDatabase",
    "PathwayDrugMapperConfig",
    "PathwayDrugMapper",
    "create_sample_drug_database",
    # Evidence
    "EvidenceLevel",
    "SafetyFlag",
    "EvidenceScore",
    "EvidenceScorerConfig",
    "EvidenceScorer",
    "create_sample_evidence_databases",
    # Ranking
    "TherapeuticHypothesis",
    "RankingConfig",
    "RankingResult",
    "HypothesisRanker",
    "create_hypothesis_ranker",
]

__version__ = "1.0.0"
